{% set name = "jupyter-rfb" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_rfb-{{ version }}.tar.gz
  sha256: 1231417ed3bcb87a804c9e3b06a200696940c9349ec13f9ab08a507d4fd439cb

build:
  number: 0
  noarch: python

requirements:
  run_constrained:
    - jupyterlab >=3.0
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - pip
    - python >=3.9
  run:
    - ipywidgets >=7.6.0,<9.0.0
    - numpy
    - python >=3.9
    - pillow

test:
  imports:
    - jupyter_rfb
  requires:
    - pip
    - jupyterlab
    - pytest
  source_files:
    - tests/*.py
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "jupyter_rfb.*OK.*jupyter_rfb"  # [unix]
    - pytest ./tests

about:
  home: https://github.com/vispy/jupyter_rfb
  summary: Remote Frame Buffer for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djhoese
    - almarklein
