{% set name = "jupyter-rfb" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_rfb-{{ version }}.tar.gz
  sha256: 0dca691aeccae11513051a850185e310148febef8f29f12b2b78f86539538995

build:
  number: 0
  noarch: python

requirements:
  run_constrained:
    - jupyterlab >=3.0
  host:
    - jupyter-packaging >=0.7.9,<0.8
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.6.0
    - numpy
    - python >=3.6
    - pillow

test:
  imports:
    - jupyter_rfb
  requires:
    - pip
    - jupyterlab
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "jupyter_rfb.*OK.*jupyter_rfb"  # [unix]

about:
  home: https://github.com/vispy/jupyter_rfb
  summary: Remote Frame Buffer for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djhoese
    - almarklein
