{% set name = "jupyter-rfb" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_rfb-{{ version }}.tar.gz
  sha256: 45549b1b36614195f76d33a1c299b21628d5aa4b3b4ed9a4b49b4888c98b2191

build:
  number: 0
  noarch: python

requirements:

  host:
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab
    - yarn >=1.22,<2
    - pip
    - python {{ python_min }}
  run:
    - ipywidgets >=7.6.0,<9.0.0
    - numpy
    - python >={{ python_min }}
    - pillow
  run_constrained:
    - jupyterlab >=3.0

test:
  imports:
    - jupyter_rfb
  requires:
    - pip
    - jupyterlab
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "jupyter_rfb.*OK.*jupyter_rfb"  # [unix]

about:
  home: https://github.com/vispy/jupyter_rfb
  summary: Remote Frame Buffer for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kushalkolar
    - djhoese
    - almarklein
